// Generated by CodiumAI

import HistoryView from "./historyView";

describe("HistoryView", () => {});

// Test that the HistoryView component renders a table with the correct headers and data
it("should render a table with headers and data", () => {
  // Arrange
  const data = [
    {
      createdOn: 1635724800000,
      views: 10,
      link: "https://example.com",
      expires: 1635728400000,
    },
    {
      createdOn: 1635728400000,
      views: 5,
      link: "https://example2.com",
      expires: 1635732000000,
    },
  ];

  // Act
  const wrapper = shallow(<HistoryView data={data} />);

  // Assert
  expect(wrapper.find("th")).toHaveLength(5);
  expect(wrapper.find("td")).toHaveLength(10);
  expect(wrapper.find("td").at(0).text()).toBe("https://example.com");
  expect(wrapper.find("td").at(1).text()).toBe("10");
  expect(wrapper.find("td").at(2).text()).toBe("1635724800000");
  expect(wrapper.find("td").at(3).text()).toBe("1635728400000");
  expect(wrapper.find("td").at(4).text()).toBe("https://example2.com");
  expect(wrapper.find("td").at(5).text()).toBe("5");
  expect(wrapper.find("td").at(6).text()).toBe("1635728400000");
  expect(wrapper.find("td").at(7).text()).toBe("1635732000000");
});
