import {
  MdAddLink,
  MdAudiotrack,
  MdSecurity,
  MdVideoLibrary,
} from "react-icons/md";
import {
  AiFillHeart,
  AiFillFileAdd,
  AiOutlineQrcode,
  AiFillEye,
  AiFillFacebook,
  AiOutlineTwitter,
  AiOutlineInstagram,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillWechat,
  AiOutlineBehanceSquare,
  AiFillSkype,
  AiFillMediumSquare,
  AiFillDribbbleCircle,
  AiOutlineMail,
  AiOutlineFile,
  AiFillPhone,
} from "react-icons/ai";
import { RiCustomerService2Fill } from "react-icons/ri";
import {
  BsPinAngleFill,
  BsFillShareFill,
  BsPinterest,
  BsTiktok,
  BsSnapchat,
  BsReddit,
  BsWhatsapp,
  BsTelegram,
  BsVimeo,
  BsQuora,
  BsFillFileEarmarkImageFill,
} from "react-icons/bs";
import { HiOutlineLogout } from "react-icons/hi";
import { IoSettingsSharp } from "react-icons/io5";
import { RxAvatar } from "react-icons/rx";
import { FiLink2 } from "react-icons/fi";
import { GoHomeFill } from "react-icons/go";
import { TbBrandGoogleAnalytics, TbWorldWww } from "react-icons/tb";
import {
  FaMeetup,
  FaMix,
  FaSoundcloud,
  FaTumblr,
  FaViber,
  FaXing,
} from "react-icons/fa";
import { BiLink, BiLogoFlickr, BiLogoPeriscope, BiText } from "react-icons/bi";
import { SiMyspace } from "react-icons/si";
import { PropertyState, colorProps, socialMediaTypes } from "@/Types/types";

type linksProps = {
  id: number;
  path: string;
  name: string;
};

type useByProps = {
  id: number;
  name: string;
  icon: string;
};

type whyUsProps = {
  id: number;
  name: string;
  icon?: React.ReactElement | null;
  note: string;
};

type howItWorksProps = {
  id: number;
  name: string;
  icon: React.ReactElement | null;
  note: string;
};

type konectFeaturesProps = {
  id: number;
  more: string;
  title: string;
};

export type appNavProps = {
  id: number;
  name: string;
  path: string;
  icon: React.ReactElement;
};

type sideBarProps = {
  id: number;
  name: string;
  path: string;
  icon: React.ReactElement;
};

type bgType = {
  type: "image" | "color" | "gradient";
};

type btnTypes = {
  type: "glassmorphism" | "solid" | "old-fashion";
};

export const Links: linksProps[] = [
  {
    id: 1,
    path: "#home",
    name: "Home",
  },
  {
    id: 2,
    path: "#whyus",
    name: "Why us",
  },
  {
    id: 3,
    path: "#howitworks",
    name: "How it works",
  },
  {
    id: 4,
    path: "#shortenlink",
    name: "Shorten link",
  },
  {
    id: 5,
    path: "#features",
    name: "Features",
  },
];

export const UseBy: useByProps[] = [
  {
    id: 1,
    name: "Videographer",
    icon: "🎥",
  },
  {
    id: 2,
    name: "Content Creator",
    icon: "📝",
  },
  {
    id: 3,
    name: "Video Editor",
    icon: "🎬",
  },
  {
    id: 4,
    name: "Photographer",
    icon: "📸",
  },
  {
    id: 5,
    name: "Social Media Manager",
    icon: "📱",
  },
  {
    id: 6,
    name: "Graphic Designer",
    icon: "🎨",
  },
  {
    id: 7,
    name: "Web Content Creator",
    icon: "🌐",
  },
  {
    id: 8,
    name: "Copywriter",
    icon: "🖋️",
  },
  {
    id: 9,
    name: "Podcast Producer",
    icon: "🎙️",
  },
  {
    id: 10,
    name: "Animator",
    icon: "🎞️",
  },
  {
    id: 11,
    name: "Sound Designer",
    icon: "🎧",
  },
  {
    id: 12,
    name: "Music Composer",
    icon: "🎵",
  },
  {
    id: 13,
    name: "Content Strategist",
    icon: "📊",
  },
  {
    id: 14,
    name: "Video Game Developer",
    icon: "🎮",
  },
  {
    id: 15,
    name: "Influencer",
    icon: "🤳",
  },
  {
    id: 16,
    name: "Art Director",
    icon: "🎨",
  },
  {
    id: 17,
    name: "Content Marketing Manager",
    icon: "📈",
  },
  {
    id: 18,
    name: "UX/UI Designer",
    icon: "🖌️",
  },
  {
    id: 19,
    name: "Motion Graphics Designer",
    icon: "💫",
  },
  {
    id: 20,
    name: "E-Learning Content Developer",
    icon: "📚",
  },
  {
    id: 21,
    name: "Virtual Reality (VR) Content Creator",
    icon: "🕶️",
  },
  {
    id: 22,
    name: "Technical Writer",
    icon: "📄",
  },
  {
    id: 23,
    name: "Social Media Influencer Manager",
    icon: "👤",
  },
  {
    id: 24,
    name: "Content Analyst",
    icon: "🔍",
  },
  {
    id: 25,
    name: "Audio Engineer",
    icon: "🎛️",
  },
  {
    id: 26,
    name: "Broadcast Journalist",
    icon: "📻",
  },
  {
    id: 27,
    name: "Storyboard Artist",
    icon: "📜",
  },
  {
    id: 28,
    name: "Brand Strategist",
    icon: "🚀",
  },
  {
    id: 29,
    name: "Content Moderator",
    icon: "👀",
  },
  {
    id: 30,
    name: "Streaming Content Producer",
    icon: "🎥",
  },
];

export const whyUsReasons: whyUsProps[] = [
  {
    id: 1,
    name: "99% Secured with data encryption",
    icon: <MdSecurity />, // Icon from the MdSecurity component (react-icons/md)
    note: "We use industry-standard encryption to protect your data.",
  },
  {
    id: 2,
    name: "It's 100% Free",
    icon: <BsPinAngleFill />,
    note: "Enjoy all our services without any cost.",
  },
  {
    id: 3,
    name: "Loved by business owners",
    icon: <AiFillHeart />, // Icon from the AiFillHeart component (react-icons/ai)
    note: "Our platform has received positive feedback from business owners.",
  },
  {
    id: 4,
    name: "24HRs Customer Support",
    icon: <RiCustomerService2Fill />, // Icon from the RiCustomerService2Fill component (react-icons/ri)
    note: "Our customer support team is available 24/7 to assist you.",
  },
];

export const HowItWorksArray: howItWorksProps[] = [
  {
    id: 1,
    name: "Sign Up",
    note: "Create an account to start using the link aggregator. Sign up with your email and choose a strong password. You can also sign up using your Google or Facebook account for a faster registration process.",
    icon: <RxAvatar />,
  },
  {
    id: 2,
    name: "Add your content",
    note: "Once you've signed up, you can start adding your favorite links to the aggregator. Organize your links into categories to keep them well-structured and easily accessible.",
    icon: <AiFillFileAdd />,
  },
  {
    id: 3,
    name: "Share on your bio",
    note: "Share your link aggregator page on your social media bio or personal website to let others discover and explore the valuable content you've curated. It's a great way to showcase your favorite resources and connect with your audience.",
    icon: <BsFillShareFill />,
  },
];

export const TestLinks = [
  {
    id: 2,
    option: "Sign up to access all features for free",
  },
  {
    id: 2,
    option: "Have access to your link analytics",
  },
  {
    id: 2,
    option: "Have access to create a link aggregator",
  },
];

export const KonnectFeatures: konectFeaturesProps[] = [
  {
    id: 1,
    title: "🌐 Connect with the World",
    more: "With Konnect, you can expand your reach and connect with a global audience effortlessly. Reach out to people from different corners of the world and build meaningful relationships. Discover new opportunities, exchange ideas, and collaborate on exciting projects with professionals from diverse backgrounds.",
  },
  {
    id: 2,
    title: "📱 Seamless Mobile Experience",
    more: "Konnect is designed to work flawlessly across all devices. Whether you're on your desktop, tablet, or smartphone, enjoy a consistent and intuitive experience on the go. Stay connected with your network wherever you are, making networking convenient and accessible at your fingertips.",
  },
  {
    id: 3,
    title: "📈 Business Opportunities",
    more: "Explore new business opportunities with Konnect's expansive network. Connect with potential partners, investors, and clients to expand your business horizons. Leverage the power of networking to propel your business forward.",
  },
  {
    id: 4,
    title: "📊 Analytics and Insights",
    more: "Gain valuable insights into your connections and interactions with in-depth analytics. Track your performance, measure engagement, and make data-driven decisions. Discover trends in your network, understand your audience better, and optimize your networking strategy for maximum impact.",
  },
  {
    id: 5,
    title: "🔒 Privacy and Security",
    more: "Your privacy matters to us. Konnect ensures top-notch security measures to safeguard your data and communications, providing you with peace of mind. Our robust security protocols and encryption technologies ensure that your interactions and information are protected from unauthorized access.",
  },
  {
    id: 6,
    title: "🎨 Customizable Profile",
    more: "Express your uniqueness with a personalized profile. Customize your page with themes, photos, and a captivating bio that truly represents you. Showcase your skills, accomplishments, and portfolio in a visually appealing way, leaving a lasting impression on your connections.",
  },
  {
    id: 7,
    title: "📱 Social Media Integration",
    more: "Seamlessly connect your social media accounts with Konnect. Share your updates, articles, and achievements with your network across different platforms. Leverage the power of social media to expand your reach and enhance your online presence.",
  },
  {
    id: 8,
    title: "🌐 Custom Domain",
    more: "Create a unique and professional identity for your profile with a custom domain. Personalize your Konnect profile with your own domain name (e.g., yourname.com) to showcase your brand and make a lasting impression on visitors.",
  },
  {
    id: 9,
    title: "📢 Broadcasts and Announcements",
    more: "Keep your audience informed with broadcast messages and announcements. Make announcements, share updates, and engage with your followers effortlessly. Leverage the power of broadcasts to reach a wider audience and ensure that your important messages are heard.",
  },
  {
    id: 10,
    title: "⭐ User-friendly Interface",
    more: "Our intuitive and user-friendly interface ensures a seamless and delightful experience for both new and experienced users. Navigate through the platform with ease, access features effortlessly, and enjoy a hassle-free networking experience that puts you in control.",
  },
];

export const SideBarNav: appNavProps[] = [
  {
    id: 1,
    name: "Home",
    path: "/home",
    icon: <GoHomeFill />,
  },
  {
    id: 2,
    name: "Link In Bio",
    path: "/linkInBio",
    icon: <FiLink2 />,
  },
  {
    id: 3,
    name: "Shorten Link",
    path: "/shortenLink",
    icon: <MdAddLink />,
  },
  {
    id: 4,
    name: "QR Code",
    path: "/qrCode",
    icon: <AiOutlineQrcode />,
  },
  {
    id: 6,
    name: "Log Out",
    path: "/logout",
    icon: <HiOutlineLogout />,
  },
];

export const uploadImageType = [
  {
    name: "Avatar",
  },
  {
    name: "Camera",
  },
  {
    name: "Upload",
  },
];

export const AppNavBar: sideBarProps[] = [
  {
    id: 2,
    name: "Preview",
    path: "/preview",
    icon: <AiFillEye />,
  },
  {
    id: 3,
    name: "Settings",
    path: "/settings",
    icon: <IoSettingsSharp />,
  },
];

export const socialMediaPlatforms: socialMediaTypes[] = [
  {
    id: 1,
    name: "Facebook",
    icon: "https://img.icons8.com/?size=512&id=118497&format=png",
    order: 1,
    color: "#1877F2",
    regex: /^(https?:\/\/)?(www\.)?facebook\.com\/.*/,
  },
  {
    id: 2,
    name: "Twitter",
    icon: "https://img.icons8.com/?size=512&id=13963&format=png",
    order: 2,
    color: "#1DA1F2",
    regex: /^(https?:\/\/)?(www\.)?twitter\.com\/.*/,
  },
  {
    id: 3,
    name: "Instagram",
    icon: "https://img.icons8.com/?size=512&id=32323&format=png",
    order: 3,
    color: "#E1306C",
    regex: /^(https?:\/\/)?(www\.)?instagram\.com\/.*/,
  },
  {
    id: 4,
    name: "LinkedIn",
    icon: "https://img.icons8.com/?size=512&id=13930&format=png",
    order: 4,
    color: "#0A66C2",
    regex: /^(https?:\/\/)?(www\.)?linkedin\.com\/.*/,
  },
  {
    id: 5,
    name: "YouTube",
    icon: "https://img.icons8.com/?size=512&id=19318&format=png",
    order: 5,
    color: "#FF0000",
    regex: /^(https?:\/\/)?(www\.)?youtube\.com\/.*/,
  },
  {
    id: 6,
    name: "Pinterest",
    icon: "https://img.icons8.com/?size=512&id=63676&format=png",
    order: 6,
    color: "#E60023",
    regex: /^(https?:\/\/)?(www\.)?pinterest\.com\/.*/,
  },
  {
    id: 7,
    name: "TikTok",
    icon: "https://img.icons8.com/?size=512&id=118640&format=png",
    order: 7,
    color: "#010101",
    regex: /^(https?:\/\/)?(www\.)?tiktok\.com\/.*/,
  },
  {
    id: 8,
    name: "Snapchat",
    icon: "https://img.icons8.com/?size=512&id=67599&format=png",
    order: 8,
    color: "#FFFC00",
    regex: /^(https?:\/\/)?(www\.)?snapchat\.com\/.*/,
  },
  {
    id: 9,
    name: "Reddit",
    icon: "https://img.icons8.com/?size=2x&id=13642&format=png",
    order: 9,
    color: "#FF5700",
    regex: /^(https?:\/\/)?(www\.)?reddit\.com\/.*/,
  },
  {
    id: 10,
    name: "Tumblr",
    icon: "https://img.icons8.com/?size=512&id=13976&format=png",
    order: 10,
    color: "#36465D",
    regex: /^(https?:\/\/)?(www\.)?tumblr\.com\/.*/,
  },
  {
    id: 11,
    name: "WhatsApp",
    icon: "https://img.icons8.com/?size=512&id=16713&format=png",
    order: 11,
    color: "#25D366",
    regex: /^(https?:\/\/)?(www\.)?whatsapp\.com\/.*/,
  },
  {
    id: 12,
    name: "WeChat",
    icon: "https://img.icons8.com/?size=512&id=19977&format=png",
    order: 12,
    color: "#07C160",
    regex: /^(https?:\/\/)?(www\.)?wechat\.com\/.*/,
  },
  {
    id: 13,
    name: "Viber",
    icon: "https://img.icons8.com/?size=512&id=44468&format=png",
    order: 13,
    color: "#7C529B",
    regex: /^(https?:\/\/)?(www\.)?viber\.com\/.*/,
  },
  {
    id: 14,
    name: "Telegram",
    icon: "https://img.icons8.com/?size=512&id=63306&format=png",
    order: 14,
    color: "#0088CC",
    regex: /^(https?:\/\/)?(www\.)?telegram\.org\/.*/,
  },
  {
    id: 15,
    name: "Skype",
    icon: "https://img.icons8.com/?size=512&id=63204&format=png",
    order: 15,
    color: "#00AFF0",
    regex: /^(https?:\/\/)?(www\.)?skype\.com\/.*/,
  },
  {
    id: 16,
    name: "Flickr",
    icon: "https://img.icons8.com/?size=512&id=20896&format=png",
    order: 16,
    color: "#0063DC",
    regex: /^(https?:\/\/)?(www\.)?flickr\.com\/.*/,
  },
  {
    id: 17,
    name: "Vimeo",
    icon: "https://img.icons8.com/?size=512&id=21048&format=png",
    order: 17,
    color: "#1AB7EA",
    regex: /^(https?:\/\/)?(www\.)?vimeo\.com\/.*/,
  },
  {
    id: 18,
    name: "Quora",
    icon: "https://img.icons8.com/?size=512&id=ewnPU99CRuAw&format=png",
    order: 18,
    color: "#B92B27",
    regex: /^(https?:\/\/)?(www\.)?quora\.com\/.*/,
  },
  {
    id: 19,
    name: "Medium",
    icon: "https://img.icons8.com/?size=512&id=GCFsv1L11D1z&format=png",
    order: 19,
    color: "#12100E",
    regex: /^(https?:\/\/)?(www\.)?medium\.com\/.*/,
  },
  {
    id: 20,
    name: "Mix",
    icon: "https://img.icons8.com/?size=512&id=OPIUCyhxbOXH&format=png",
    order: 20,
    color: "#FB8C00",
    regex: /^(https?:\/\/)?(www\.)?mix\.com\/.*/,
  },
  {
    id: 21,
    name: "Phone",
    icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
    order: 21,
    color: "#0A0A0A",
    regex: /^[0-9]+$/,
  },
  {
    id: 22,
    name: "SoundCloud",
    icon: "https://img.icons8.com/?size=512&id=13669&format=png",
    order: 22,
    color: "#FF5500",
    regex: /^(https?:\/\/)?(www\.)?soundcloud\.com\/.*/,
  },
  {
    id: 23,
    name: "Dribbble",
    icon: "https://img.icons8.com/?size=512&id=LULpAxzosrfL&format=png",
    order: 23,
    color: "#EA4C89",
    regex: /^(https?:\/\/)?(www\.)?dribbble\.com\/.*/,
  },
  {
    id: 24,
    name: "Behance",
    icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
    order: 24,
    color: "#005FF9",
    regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
  },
  {
    id: 25,
    name: "XING",
    icon: "https://img.icons8.com/?size=512&id=mGyune7hynBJ&format=png",
    order: 25,
    color: "#026466",
    regex: /^(https?:\/\/)?(www\.)?xing\.com\/.*/,
  },
  {
    id: 26,
    name: "Meetup",
    icon: "https://img.icons8.com/?size=512&id=102680&format=png",
    order: 26,
    color: "#F33D60",
    regex: /^(https?:\/\/)?(www\.)?meetup\.com\/.*/,
  },
  {
    id: 27,
    name: "Periscope",
    icon: "https://img.icons8.com/?size=512&id=124362&format=png",
    order: 27,
    color: "#40A4C8",
    regex: /^(https?:\/\/)?(www\.)?periscope\.tv\/.*/,
  },
  {
    id: 28,
    name: "MySpace",
    icon: "https://img.icons8.com/?size=512&id=60446&format=png",
    order: 28,
    color: "#000000",
    regex: /^(https?:\/\/)?(www\.)?myspace\.com\/.*/,
  },
];

export const contentsToAdd = [
  {
    id: 1,
    name: "URL Button",
    icon: <BiLink />,
    desc: "Open a web page to a specific URL",
  },
  {
    id: 2,
    name: "Email Button",
    icon: <AiOutlineMail />,
    desc: "Open an email to a specific address",
  },
  {
    id: 3,
    name: "File Button",
    icon: <AiOutlineFile />,
    desc: "Open an uploaded file(PDF or Image)",
  },
  {
    id: 6,
    name: "Audio",
    icon: <MdAudiotrack />,
    desc: "Embed your audio file",
  },
  {
    id: 7,
    name: "Video",
    icon: <MdVideoLibrary />,
    desc: "Embed your video file",
  },
  {
    id: 8,
    name: "Text",
    icon: <BiText />,
    desc: "Tell your page story",
  },
];

export const buttontypes = [
  {
    id: 1,
    type: "File download",
  },
  {
    id: 2,
    type: "Url",
  },
  {
    id: 4,
    type: "Email",
  },
];

export const animationTypes = [
  {
    id: 1,
    type: "blick",
  },
  {
    id: 2,
    type: "bounce",
  },
  {
    id: 3,
    type: "pulse",
  },
  {
    id: 4,
    type: "none",
  },
];

export const bgTypes: bgType[] = [
  {
    type: "image",
  },
  {
    type: "color",
  },
  {
    type: "gradient",
  },
];

export const btnTypes: btnTypes[] = [
  {
    type: "glassmorphism",
  },
  {
    type: "old-fashion",
  },
  {
    type: "solid",
  },
];

export const oldFashionBtn = {
  "--key-text-color": "#969faf",
  "--docsearch-key-shadow":
    "inset 0 -2px 0 0 #cdcde6, inset 0 0 1px 1px #fff, 0 1px 2px 1px rgba(30, 35, 90, 0.4)",
  "--docsearch-key-gradient": "linear-gradient(-225deg, #d5dbe4, #f8f8f8)",
  background: "var(--docsearch-key-gradient)",
  color: "var(--key-text-color)",
  height: "3rem",
  textAlign: "center",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  minWidth: "1em",
};

export const fontTypes: {
  id: number;
  fontName: string;
  types: "Ubuntu" | "Libre" | "Spectral" | "OpenSans";
}[] = [
  {
    id: 1,
    fontName: "Ubuntu",
    types: "Ubuntu",
  },
  {
    id: 2,
    fontName: "Libre",
    types: "Libre",
  },
  {
    id: 3,
    fontName: "Spectral",
    types: "Spectral",
  },
  {
    id: 3,
    fontName: "Open Sans",
    types: "OpenSans",
  },
];

export const examplebtn = [
  {
    name: "Button 1",
  },
  {
    name: "Button 2",
  },
  {
    name: "Button 3",
  },
  {
    name: "Button 4",
  },
  {
    name: "Button 5",
  },
];

export const shareProfileTo = [
  {
    id: 1,
    name: "WhatsApp",
    icon: "https://img.icons8.com/?size=512&id=DUEq8l5qTqBE&format=png",
  },
  {
    id: 2,
    name: "Twitter",
    icon: "https://img.icons8.com/?size=512&id=KxHlias9AgZt&format=png",
  },
  {
    id: 3,
    name: "SnapChat",
    icon: "https://img.icons8.com/?size=512&id=7VKXHaMW3lGB&format=png",
  },
];

export const generateRandomDesign: PropertyState[] = [
  {
    socialMedia: [
      {
        id: 1,
        name: "Facebook",
        icon: "https://img.icons8.com/?size=512&id=118497&format=png",
        order: 1,
        color: "#1877F2",
        regex: /^(https?:\/\/)?(www\.)?facebook\.com\/.*/,
        link: "",
      },
      {
        id: 2,
        name: "Twitter",
        icon: "https://img.icons8.com/?size=512&id=13963&format=png",
        order: 2,
        color: "#1DA1F2",
        regex: /^(https?:\/\/)?(www\.)?twitter\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Simplicity is the key to happiness",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 10,
    backgroundType: "gradient",
    haveSecondary: false,
    backgroundImage: "",
    backgroundColor: "",
    secondaryBGColor: "",
    buttonShadow: "none",
    buttonColor: "",
    buttonBorderRadius: 30,
    font: "OpenSans",
    enableShareButton: true,
    buttonType: "glassmorphism",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#252525",
    gap: 60,
    buttonBackgroundColor: "",
    hideName: false,
    firstColor: "#ff0101",
    secondColor: "#eecdcd",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 23,
        name: "Dribbble",
        icon: "https://img.icons8.com/?size=512&id=LULpAxzosrfL&format=png",
        order: 23,
        color: "#EA4C89",
        regex: /^(https?:\/\/)?(www\.)?dribbble\.com\/.*/,
        link: "",
      },
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
      {
        id: 14,
        name: "Telegram",
        icon: "https://img.icons8.com/?size=512&id=63306&format=png",
        order: 14,
        color: "#0088CC",
        regex: /^(https?:\/\/)?(www\.)?telegram\.org\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Video creator",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "image",
    haveSecondary: false,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#252525",
    buttonBorderRadius: 65,
    font: "OpenSans",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#eeeeee",
    gap: 55,
    buttonBackgroundColor: "#ffff",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 11,
        name: "WhatsApp",
        icon: "https://img.icons8.com/?size=512&id=16713&format=png",
        order: 11,
        color: "#25D366",
        regex: /^(https?:\/\/)?(www\.)?whatsapp\.com\/.*/,
        link: "",
      },
      {
        id: 8,
        name: "Snapchat",
        icon: "https://img.icons8.com/?size=512&id=67599&format=png",
        order: 8,
        color: "#FFFC00",
        regex: /^(https?:\/\/)?(www\.)?snapchat\.com\/.*/,
        link: "",
      },
      {
        id: 9,
        name: "Reddit",
        icon: "https://img.icons8.com/?size=2x&id=13642&format=png",
        order: 9,
        color: "#FF5700",
        regex: /^(https?:\/\/)?(www\.)?reddit\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Am not perfect but am unique and special",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "color",
    haveSecondary: false,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "#a38b08",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#FFFFF",
    buttonBorderRadius: 65,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#ffff",
    gap: 55,
    buttonBackgroundColor: "#fcfc08",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 23,
        name: "Dribbble",
        icon: "https://img.icons8.com/?size=512&id=LULpAxzosrfL&format=png",
        order: 23,
        color: "#EA4C89",
        regex: /^(https?:\/\/)?(www\.)?dribbble\.com\/.*/,
        link: "",
      },
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
      {
        id: 1,
        name: "Facebook",
        icon: "https://img.icons8.com/?size=512&id=118497&format=png",
        order: 1,
        color: "#1877F2",
        regex: /^(https?:\/\/)?(www\.)?facebook\.com\/.*/,
        link: "",
      },
      {
        id: 2,
        name: "Twitter",
        icon: "https://img.icons8.com/?size=512&id=13963&format=png",
        order: 2,
        color: "#1DA1F2",
        regex: /^(https?:\/\/)?(www\.)?twitter\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "I live life on my own terms with my own rules and attitude",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "color",
    haveSecondary: true,
    backgroundImage: "",
    backgroundColor: "#c6360e",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#ffffff",
    buttonBorderRadius: 0,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 30,
    textColor: "#c6360e",
    gap: 55,
    buttonBackgroundColor: "#c6360e",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage:
      "https://i.ibb.co/sKc33dR/sabri-tuzcu-g-er-Oiu-Dxro-unsplash-1.jpg",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 23,
        name: "Dribbble",
        icon: "https://img.icons8.com/?size=512&id=LULpAxzosrfL&format=png",
        order: 23,
        color: "#EA4C89",
        regex: /^(https?:\/\/)?(www\.)?dribbble\.com\/.*/,
        link: "",
      },
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
      {
        id: 2,
        name: "Twitter",
        icon: "https://img.icons8.com/?size=512&id=13963&format=png",
        order: 2,
        color: "#1DA1F2",
        regex: /^(https?:\/\/)?(www\.)?twitter\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "my own rules and attitude",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "color",
    haveSecondary: false,
    backgroundImage: "",
    backgroundColor: "#b3d8f3",
    secondaryBGColor: "",
    buttonShadow: "solid",
    buttonColor: "#ffffff",
    buttonBorderRadius: 70,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#e4e4e4",
    gap: 55,
    buttonBackgroundColor: "#e4e4e4",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage:
      "https://i.ibb.co/P6R01xm/johannes-plenio-qkfx-Bc2-NQ18-unsplash-1.jpg",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
      {
        id: 2,
        name: "Twitter",
        icon: "https://img.icons8.com/?size=512&id=13963&format=png",
        order: 2,
        color: "#1DA1F2",
        regex: /^(https?:\/\/)?(www\.)?twitter\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Live is so short so lets smile and  enjoy it while we can",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 10,
    backgroundType: "gradient",
    haveSecondary: false,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "#FFFF",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#ffff",
    buttonBorderRadius: 20,
    font: "Spectral",
    enableShareButton: true,
    buttonType: "glassmorphism",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 50,
    textColor: "#ea00ff",
    gap: 55,
    buttonBackgroundColor: "#6d530e",
    hideName: false,
    firstColor: "#ff0095",
    secondColor: "#6a646a",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
      {
        id: 2,
        name: "Twitter",
        icon: "https://img.icons8.com/?size=512&id=13963&format=png",
        order: 2,
        color: "#1DA1F2",
        regex: /^(https?:\/\/)?(www\.)?twitter\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Live life to the fullest and focus on the positive.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "color",
    haveSecondary: false,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "#e09bf9",
    secondaryBGColor: "",
    buttonShadow: "none",
    buttonColor: "#ffff",
    buttonBorderRadius: 20,
    font: "Libre",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#fffff",
    gap: 85,
    buttonBackgroundColor: "#65536d",
    hideName: false,
    firstColor: "#ff0095",
    secondColor: "#6a646a",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Believe in yourself, and you will be unstoppable.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 20,
    backgroundType: "color",
    haveSecondary: false,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "#e09bf9",
    secondaryBGColor: "",
    buttonShadow: "solid",
    buttonColor: "#252525",
    buttonBorderRadius: 20,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#252525",
    gap: 70,
    buttonBackgroundColor: "#ffff",
    hideName: true,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 20,
        name: "Mix",
        icon: "https://img.icons8.com/?size=512&id=OPIUCyhxbOXH&format=png",
        order: 20,
        color: "#FB8C00",
        regex: /^(https?:\/\/)?(www\.)?mix\.com\/.*/,
        link: "",
      },
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
      {
        id: 22,
        name: "SoundCloud",
        icon: "https://img.icons8.com/?size=512&id=13669&format=png",
        order: 22,
        color: "#FF5500",
        regex: /^(https?:\/\/)?(www\.)?soundcloud\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Making the ordinary extraordinary.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 20,
    backgroundType: "color",
    haveSecondary: false,
    backgroundImage: "",
    backgroundColor: "#252525",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#252525",
    buttonBorderRadius: 20,
    font: "OpenSans",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#dad7db",
    gap: 70,
    buttonBackgroundColor: "#dad7db",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 24,
        name: "Behance",
        icon: "https://img.icons8.com/?size=512&id=FL6PSxZ78xbv&format=png",
        order: 24,
        color: "#005FF9",
        regex: /^(https?:\/\/)?(www\.)?behance\.net\/.*/,
        link: "",
      },
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
      {
        id: 22,
        name: "SoundCloud",
        icon: "https://img.icons8.com/?size=512&id=13669&format=png",
        order: 22,
        color: "#FF5500",
        regex: /^(https?:\/\/)?(www\.)?soundcloud\.com\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Living one day at a time.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 20,
    backgroundType: "color",
    haveSecondary: true,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "#fffff",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#eeee",
    buttonBorderRadius: 0,
    font: "OpenSans",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 80,
    textColor: "#252525",
    gap: 100,
    buttonBackgroundColor: "#4d4c4c",
    hideName: true,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage:
      "https://i.ibb.co/f2hsWjf/luca-bravo-XJXWbf-So2f0-unsplash-1.jpg",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "On a journey called life.",
    socialMediaIconSize: 25,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "color",
    haveSecondary: true,
    backgroundImage: "", //TODO:Add background image
    backgroundColor: "#f788ee",
    secondaryBGColor: "#fffff",
    buttonShadow: "soft",
    buttonColor: "#fffff",
    buttonBorderRadius: 50,
    font: "Spectral",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#fffff",
    gap: 100,
    buttonBackgroundColor: "#4d4c4c",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Striving for greatness.",
    socialMediaIconSize: 25,
    addBorderToSocialIcon: false,
    profilePictureShadow: 0,
    backgroundType: "image",
    haveSecondary: false,
    backgroundImage:
      "https://i.ibb.co/grDd9Pw/jeremy-thomas-O6-N9-RV2rz-X8-unsplash-1.jpg",
    backgroundColor: "",
    secondaryBGColor: "",
    buttonShadow: "none",
    buttonColor: "#252525",
    buttonBorderRadius: 50,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#fffff",
    gap: 100,
    buttonBackgroundColor: "#fba801",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: true,
  },
  {
    socialMedia: [
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Exploring the world one step at a time.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: true,
    profilePictureShadow: 0,
    backgroundType: "color",
    haveSecondary: true,
    backgroundImage: "",
    backgroundColor: "#d2f9d1",
    secondaryBGColor: "#0f9b0a",
    buttonShadow: "soft",
    buttonColor: "#ffffff",
    buttonBorderRadius: 50,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#0f9b0a",
    gap: 100,
    buttonBackgroundColor: "#0f9b0a",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 26,
        name: "Meetup",
        icon: "https://img.icons8.com/?size=512&id=102680&format=png",
        order: 26,
        color: "#F33D60",
        regex: /^(https?:\/\/)?(www\.)?meetup\.com\/.*/,
        link: "",
      },
      {
        id: 27,
        name: "Periscope",
        icon: "https://img.icons8.com/?size=512&id=124362&format=png",
        order: 27,
        color: "#40A4C8",
        regex: /^(https?:\/\/)?(www\.)?periscope\.tv\/.*/,
        link: "",
      },
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Chasing dreams and catching them.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: true,
    profilePictureShadow: 0,
    backgroundType: "image",
    haveSecondary: false,
    backgroundImage:
      "https://i.ibb.co/SP47ssd/zoltan-tasi-HQPJEEj-Hq-SE-unsplash-1.jpg",
    backgroundColor: "",
    secondaryBGColor: "",
    buttonShadow: "none",
    buttonColor: "#252525",
    buttonBorderRadius: 10,
    font: "Ubuntu",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 90,
    textColor: "#eeeeee",
    gap: 100,
    buttonBackgroundColor: "#ffffff",
    hideName: true,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage: "",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 21,
        name: "Phone",
        icon: "https://img.icons8.com/?size=512&id=I24lanX6Nq71&format=png",
        order: 21,
        color: "#0A0A0A",
        regex: /^[0-9]+$/,
        link: "",
      },
      {
        id: 27,
        name: "Periscope",
        icon: "https://img.icons8.com/?size=512&id=124362&format=png",
        order: 27,
        color: "#40A4C8",
        regex: /^(https?:\/\/)?(www\.)?periscope\.tv\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Turning dreams into reality.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 15,
    backgroundType: "color",
    haveSecondary: true,
    backgroundImage: "",
    backgroundColor: "#575757",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "#575757",
    buttonBorderRadius: 0,
    font: "OpenSans",
    enableShareButton: true,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#fdff76",
    gap: 100,
    buttonBackgroundColor: "#fdff76",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Color",
    secondaryImage:
      "https://i.ibb.co/SP47ssd/zoltan-tasi-HQPJEEj-Hq-SE-unsplash-1.jpg",
    hideBio: false,
    hideSocial: false,
  },
  {
    socialMedia: [
      {
        id: 27,
        name: "Periscope",
        icon: "https://img.icons8.com/?size=512&id=124362&format=png",
        order: 27,
        color: "#40A4C8",
        regex: /^(https?:\/\/)?(www\.)?periscope\.tv\/.*/,
        link: "",
      },
    ],
    profilePicture: "",
    profileBio: "Creating moments that matter.",
    socialMediaIconSize: 21,
    addBorderToSocialIcon: false,
    profilePictureShadow: 10,
    backgroundType: "color",
    haveSecondary: true,
    backgroundImage: "",
    backgroundColor: "#ffffff",
    secondaryBGColor: "",
    buttonShadow: "soft",
    buttonColor: "ffffff", //TODO
    buttonBorderRadius: 10,
    font: "Spectral",
    enableShareButton: false,
    buttonType: "solid",
    buttonProps: [],
    audio: "",
    video: "",
    text: "",
    bioCollapse: false,
    profilePicBorder: 100,
    textColor: "#575757",
    gap: 100,
    buttonBackgroundColor: "#d0b489",
    hideName: false,
    firstColor: "",
    secondColor: "",
    isLinear: false,
    secondaryTypes: "Image",
    secondaryImage:
      "https://i.ibb.co/M7yktsp/zoltan-tasi-HQPJEEj-Hq-SE-unsplash-2.jpg",
    hideBio: false,
    hideSocial: false,
  },
];

export const colors: colorProps[] = [
  { name: "Red", code: "#FF0000" },
  { name: "Green", code: "#00FF00" },
  { name: "Blue", code: "#0000FF" },
  { name: "Yellow", code: "#FFFF00" },
  { name: "Cyan", code: "#00FFFF" },
  { name: "Magenta", code: "#FF00FF" },
  { name: "Black", code: "#000000" },
  { name: "White", code: "#FFFFFF" },
  { name: "Gray", code: "#808080" },
  { name: "Orange", code: "#FFA500" },
  { name: "Purple", code: "#800080" },
  { name: "Pink", code: "#FFC0CB" },
  { name: "Brown", code: "#A52A2A" },
  { name: "Teal", code: "#008080" },
  { name: "Indigo", code: "#4B0082" },
  { name: "Gold", code: "#FFD700" },
  { name: "Silver", code: "#C0C0C0" },
  { name: "Maroon", code: "#800000" },
  { name: "Navy", code: "#000080" },
];
